### ISSUE TITLE
ngx_cache_purge v1.2 incompatible with nginx-1.0.1

### ISSUE THREAD

**Issue by maage** [FRiCKLE/ngx_cache_purge#1]
ngx_cache_purge/ngx_cache_purge_module.c: In function 'ngx_http_file_cache_purge':
ngx_cache_purge/ngx_cache_purge_module.c:681: error: 'ngx_http_file_cache_node_t' has no member named 'length'

**Comment by PiotrSikora** [comment]
Thanks for the report, I'm aware of this. New release should be out in a few minutes.
