### ISSUE TITLE
Official support on 1.4.x?

### ISSUE THREAD

**Issue by jthingelstad** [FRiCKLE/ngx_cache_purge#12]
It appears that this module compiles fine with 1.4.0 and 1.4.1. The README only reports through 1.3.x. Would be good to update it to know that it is okay.

**Comment by nikolay** [comment]
+1

**Comment by iiro** [comment]
Has anyone tested this with Nginx 1.6 version yet...? I will soon...

**Comment by nikolay** [comment]
It works on v1.6 and v1.7 for me.

**Comment by tuapuikia** [comment]
Do you use /purge or / location?

**Comment by nikolay** [comment]
I use /purge.

**Comment by PiotrSikora** [comment]
It works fine for anything between 0.7.60 and 1.7.0 (latest as of writing this).

**Comment by iiro** [comment]
Yep, we´re running this in very heavy production using 1.6.0.
