### ISSUE TITLE
Purge failure creates file not found message

### ISSUE THREAD

**Issue by runningman84** [FRiCKLE/ngx_cache_purge#14]
In case the proxy purge or slowfs purge modul does not find a file to delete, an error message like this is written:

2013/12/06 09:31:53 [error] 5399#0: *20150750 open() "/srv/htdocs/purge/o/y/jh/image450x352.jpg" failed (2: No such file or directory), client: 10.172.252.136, server: images.example.de, request: "HEAD /purge/o/y/jh/image450x352.jpg HTTP/1.1", host: "10.1.1.1"

This error is missleading, the modul should catch all request and do not pass the request to the normal nginx file handling...

**Comment by PiotrSikora** [comment]
That doesn't seem right, I'm pretty sure you misconfigured nginx.

Feel free to reopen if you can provide more data (at least: configuration, request & error.log entry).
