### ISSUE TITLE
Clearing cache with wild card

### ISSUE THREAD

**Issue by attiks** [FRiCKLE/ngx_cache_purge#5]
Disclaimer: I read the TODO, but maybe this use case is supported
nginx.conf
    fastcgi_cache_key "$host$key_uri$cookie_OctopusCacheID"; 

so the cache gets keys like
    example.com/page-1 # anonymous user / no cookie
    example.com/page-1BONDfaa020008474173563121e9163e7cac3 # authenticated user / cookie

For the purge we execute 
    curl --verbose --header 'Host:example.com' 'http://127.0.0.1:8888/purge/page-1'

But does only clear the first key, not the second one, so to make a long story short, can we do something like
    curl --verbose --header 'Host:example.com' 'http://127.0.0.1:8888/purge/page-1**'

**Comment by attiks** [comment]
I checked the source of the fastcgi_cache_key and since it uses md5 to get the filename, this will not be possible :/

**Comment by attiks** [comment]
I created a feature request on nginx forums: http://forum.nginx.org/read.php?10,217748

**Comment by PiotrSikora** [comment]
You've read the `TODO`, so you know it's impossible to do with the current cache implementation.

The suffix idea isn't bad, but it would work only for very specific use-cases and outside of nginx's API, so I'm a bit reluctant to add it.

**Comment by attiks** [comment]
Well I'm hoping nginx will allow the feature request for the API change ;p

**Comment by attiks** [comment]
Just for (my own) reference: http://forum.nginx.org/read.php?29,219312,219637 which is similar
