### ISSUE TITLE
Patch for nginx-1.3.1 can't work

### ISSUE THREAD

**Issue by magicbear** [FRiCKLE/ngx_cache_purge#7]
--- a/ngx_cache_purge_module.c  2012-06-28 05:08:44.000000000 +0800
+++ b/ngx_cache_purge_module.c  2011-12-20 20:36:20.000000000 +0800
@@ -41,7 +41,7 @@ char       _ngx_http_fastcgi_cache_purge
 ngx_int_t   ngx_http_fastcgi_cache_purge_handler(ngx_http_request_t *r);
 # endif /_ NGX_HTTP_FASTCGI */

-# if (NGX_HTTP_PROXY)
+# if (NGX_HTTP_PROXY || nginx_version >= 1003002)
 char       _ngx_http_proxy_cache_purge_conf(ngx_conf_t *cf,
                 ngx_command_t *cmd, void *conf);
 ngx_int_t   ngx_http_proxy_cache_purge_handler(ngx_http_request_t *r);
@@ -76,7 +76,7 @@ static ngx_command_t  ngx_http_cache_pur
       NULL },
 # endif /_ NGX_HTTP_FASTCGI */

-# if (NGX_HTTP_PROXY)
+# if (NGX_HTTP_PROXY || nginx_version >= 1003002)
     { ngx_string("proxy_cache_purge"),
       NGX_HTTP_LOC_CONF|NGX_CONF_TAKE2,
       ngx_http_proxy_cache_purge_conf,
@@ -257,7 +257,7 @@ ngx_http_fastcgi_cache_purge_handler(ngx
 }
 # endif /\* NGX_HTTP_FASTCGI */

-# if (NGX_HTTP_PROXY)
+# if (NGX_HTTP_PROXY || nginx_version >= 1003002)
 extern ngx_module_t  ngx_http_proxy_module;

 typedef struct {

**Comment by PiotrSikora** [comment]
Fixed in 8d3b1359b9cc9f6794c5db04bd1b35a7f97a619f, thanks for the report!
